### ISSUE TITLE
spring boot 2.0.0

### ISSUE THREAD

**Issue by melodicdeath** [fintonic/versioning-spring-boot-starter#17]
Does not support spring boot 2.0.0？

**Comment by ganchix** [comment]
Not yet, I'm working on it, on some days we will have new release working with the spring boot 2.0.0.

**Comment by ganchix** [comment]
@melodicdeath if you want to see the evolution, you can see the [feature branch](https://github.com/fintonic/versioning-spring-boot-starter/tree/feature/spring2.0AndRefactorOfStarter)

**Comment by ganchix** [comment]
Done, you can found it in the version [0.8.0](https://github.com/fintonic/versioning-spring-boot-starter/tree/0.8.0)

**Comment by melodicdeath** [comment]
Thanks very much.
